name: wattadvisor
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.11.0
  - pyomo=6.5.0
  - pyyaml=6.0
  - pandas=1.5.3
  - pydantic=1.10.12
  - xarray=2023.4.2
  - cdsapi=0.6.1
  - pvlib=0.9.5
  - requests=2.29.0
  - holidays=0.27.1
  - xlsxwriter=3.1.2
  - geopandas=0.13.0
  - pytables=3.8.0
  - descartes=1.1.0
  - geoalchemy2=0.6.3
  - pip
  - pip:
    - demandlib==0.1.9
    - highspy==1.5.3
    - open_FRED-cli==0.0.1
    - windpowerlib==0.2.1
    - pipdeptree