default_interest_rate: 0.05
solver: CBC
solver_timeout: 3600
weather_data: 
  source: era5_netcdf
  path:
    netcdf: "./wattadvisor/optimization_model/data/weather.nc"
  # source: custom_csv
  # path:
  #   csv_wind: "./test.csv"
  #   csv_solar: "./test.csv"
  #   csv_temperature: "./test.csv"
parameters_path: "./wattadvisor/optimization_model/data/parameters.yaml"
logging: 
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - PID%(process)-6d - %(levelname)-7s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: model.log
      encoding: utf8
      mode: a
  loggers:
    opt_model:
      level: DEBUG
      handlers: [console, file]
      propagate: no
  root:
    level: DEBUG
    handlers: [console, file]